# Generated by Django 4.2.7 on 2023-12-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_tex',
            new_name='blog_text',
        ),
    ]
